### ISSUE TITLE
Another color input option

### ISSUE THREAD

**Issue by WinTPo** [MajekDev/HexNicks#46]
Hello, I ran into such a problem that using it through one plugin, the HEX code is replaced with a color at once before executing the command. Please add another spelling of the command, for example

before
/ nick <gradient: # 1eae98: # d8b5ff> Majekdor </gradient>

after
/ nick <gradient: 1eae98: d8b5ff> Majekdor </gradient>

**Comment by Majekdor** [comment]
I don't fully understand. So another plugin is removing the # so the gradient isn't working?

**Comment by WinTPo** [comment]
No. The ChatControl plugin, when used in it, replaces this
<gradient: # 1eae98: # d8b5ff> Majekdor

On this
<gradient::> Majekdor   - after "gradient" there is already colored text

You can add another kind of use without #, for example
<gradient: 1eae98: d8b5ff> Majekdor

**Comment by Majekdor** [comment]
There's nothing I can really do about that. It's just a plugin conflict because you're currently using two completely different methods of parsing color. I use MiniMessage and for the color parsing and that's just how the tags work. Also the fact that ChatControl is taking plain hex codes and translating them to color is pretty silly. The "community standard" since hex codes were introduced was to do something like `&#aabbcc`, not just parse any hex code seen.
