### ISSUE TITLE
ChatContolRed Integration

### ISSUE THREAD

**Issue by PrinceHatem** [MajekDev/HexNicks#95]
**Is your feature request related to a problem? Please describe.**
I can integrate Nicknames from HexNicks into tablist, nametags, and Essentials however it does not integrate into ChatControl, so for example when a player wants to message a nicked player, they have to /msg their real name and cant msg their hexnick name.

**Describe the solution you'd like**
An integration into ChatControl so that the hexnick works in their /msg.

**Additional context**
If there is a way to even make it so when a player tries to click the tab button to fill the player's real name in /msg it acts like the player does not exist and adds that player's nickname to the options in the list instead.

**Comment by Majekdor** [comment]
ChatControlRed is a plugin made by Kangarko isn't it?

**Comment by PrinceHatem** [comment]
Correct

**Comment by Majekdor** [comment]
So I tend to steer clear of anything made by Kangarko just out of principle because of the issues he's caused on SpigotMC.

But in this case even if I looked past that I have no way to interact with ChatControlRed from HexNicks. There is no public API. I would have to buy or get the jar file in some other way and then reference that, which for a number of reasons isn't something that makes sense or that I'm willing to do.

Sorry that there's not much that can be done about this issue. HexNicks does have an api and honestly this seems more like a situation where ChatControlRed should support nickname plugins.
